server:
  port: 4444


spring:
  application:
    name: CHAT-NOTIFICATION-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/Event_Rabbiter_Chat_Service

eureka:
  client:
    registry-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/